// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lslobzzerneeullaizjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzbG9ienplcm5lZXVsbGFpempvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzIzNDAsImV4cCI6MjA2NDAwODM0MH0.ASm0u9YZRF8W9TvJZ61go8_oRSN8kongx2ZjNlFKKv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});